DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS entry;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  emp_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  section TEXT NOT NULL,
  data TEXT NOT NULL,
  FOREIGN KEY (emp_id) REFERENCES user (id)
);
